language: java

jdk:
  - openjdk11

cache:
  directories:
    - $HOME/.m2/repository/

env:
  - SPRING_PROFILES_ACTIVE=ci

before_script:
  - export PATH=$PATH:$HOME/bin/

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -U

script:
  -  mvn -X -e verify deploy
  - ./build-osx.sh